title: Senior Mobile Applications Engineer
description: Android, Kotlin, Java, Gradle, Jetpack Compose, Coroutines, Rx, Dagger
show_downloads: true
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
